MUFASAPAY_KEYSTORE_PATH="/Users/berhanu.tarekegn/git/mufasa_paymentverifier/release-key.jks"
MUFASAPAY_KEYSTORE_PASSWORD="Bmequanint$1"
MUFASAPAY_KEY_ALIAS="mufasapay"
MUFASAPAY_KEY_PASSWORD="Bmequanint$1"

